# 基础镜像
FROM redis
# author
MAINTAINER jmall

# 挂载目录
VOLUME /home/jmall/redis
# 创建目录
RUN mkdir -p /home/jmall/redis
# 指定路径
WORKDIR /home/jmall/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/jmall/redis/redis.conf
