# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER jmall

# 挂载目录
VOLUME /home/jmall
# 创建目录
RUN mkdir -p /home/jmall
# 指定路径
WORKDIR /home/jmall
# 复制jar文件到路径
COPY ./jar/jmall-auth.jar /home/jmall/jmall-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","jmall-auth.jar"]