# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER jmall

# 挂载目录
VOLUME /home/jmall
# 创建目录
RUN mkdir -p /home/jmall
# 指定路径
WORKDIR /home/jmall
# 复制jar文件到路径
COPY ./jar/jmall-modules-job.jar /home/jmall/jmall-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","jmall-modules-job.jar"]